services:
  app:
    build: .
    restart: on-failure
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service_db
    networks:
      - default
      - chesstracker

networks:
  chesstracker:
    external: true
